version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    mem_limit: 4g
    container_name: ollama
    ports:
      - "11434:11434"  
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - ai-net
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8080:8080" 
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    depends_on:
      - ollama
    networks:
      - ai-net
    restart: unless-stopped


networks:
  ai-net:
    name: ollama_openwebui_net
    driver: bridge

volumes:
  ollama-data:
