version: "3.8"

services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: ./docker.env
    ports:
      - "3001:3000"  
    volumes:
      - outline-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    networks:
      - outline-net

  redis:
    image: redis:alpine
    command: ["redis-server"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - outline-net

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - outline-net

volumes:
  outline-data:
  pg-data:

networks:
  outline-net:
